// songs used here are not owned by me 
// lyrics are modified to fit the purpose of the sketch

let song1Data = {
  title: "Never Gonna Give You Up",
  artist: "Rick Astly",
  genre: "Pop",
  mv_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  lyrics: [
    "We're no strangers to love.",
    "You know the rules and so do I.",
    "A full commitment's what I'm thinking of.",
    "You wouldn't get this from any other guy.",
    "I just wanna tell you how I'm feeling,",
    "gotta make you understand.",
    "Never gonna give you up,",
    "never gonna let you down,",
    "never gonna run around and desert you.",
    "Never gonna make you cry,",
    "never gonna say goodbye,",
    "never gonna tell a lie and hurt you.",
    "We've known each other for so long.",
    "Your heart's been aching but you're too shy to say it.",
    "Inside we both know what's been going on.",
    "We know the game and we're gonna play it.",
    "And if you ask me how I'm feeling,",
    "don't tell me you're too blind to see.",
    "Never gonna give you up,",
    "never gonna let you down,",
    "never gonna run around and desert you.",
    "Never gonna make you cry,",
    "never gonna say goodbye,",
    "never gonna tell a lie and hurt you.",
    "Never gonna give you up,",
    "never gonna let you down,",
    "never gonna run around and desert you.",
    "Never gonna make you cry,",
    "never gonna say goodbye,",
    "never gonna tell a lie and hurt you.",
    "Never gonna give, never gonna give,",
    "give you up.",
    "We've known each other for so long.",
    "Your heart's been aching but you're too shy to say it.",
    "Inside we both know what's been going on.",
    "We know the game and we're gonna play it.",
    "I just wanna tell you how I'm feeling,",
    "gotta make you understand.",
    "Never gonna give you up,",
    "never gonna let you down,",
    "never gonna run around and desert you.",
    "Never gonna make you cry,",
    "never gonna say goodbye,",
    "never gonna tell a lie and hurt you.",
  ],
};

let song2Data = {
  title: "All Star",
  artist: "Smash Mouth",
  genre: "Rock",
  mv_url: "https://www.youtube.com/watch?v=L_jWHffIx5E",
  lyrics: [
    "Somebody once told me the world is gonna roll me,",
    "I ain't the sharpest tool in the shed.",
    "She was looking kind of dumb with her finger and her thumb",
    'in the shape of an "L" on her forehead.',
    "Well the years start coming and they don't stop coming.",
    "Fed to the rules and I hit the ground running.",
    "Didn't make sense not to live for fun.",
    "Your brain gets smart but your head gets dumb.",
    "So much to do, so much to see,",
    "so what's wrong with taking the back streets?",
    "You'll never know if you don't go.",
    "You'll never shine if you don't glow.",
    "Hey now, you're an all-star, get your game on, go play.",
    "Hey now, you're a rock star, get the show on, get paid.",
    "And all that glitters is gold,",
    "only shooting stars break the mold.",
    "It's a cool place and they say it gets colder.",
    "You're bundled up now, wait 'til you get older.",
    "But the meteor men beg to differ,",
    "judging by the hole in the satellite picture.",
    "The ice we skate is getting pretty thin,",
    "The water's getting warm so you might as well swim.",
    "My world's on fire, how about yours?",
    "That's the way I like it and I'll never get bored.",
    "Hey now, you're an all-star, get your game on, go play.",
    "Hey now, you're a rock star, get the show on, get paid.",
    "All that glitters is gold,",
    "only shooting stars break the mold.",
    "Hey now, you're an all-star, get your game on, go play.",
    "Hey now, you're a rock star, get the show on, get paid.",
    "All that glitters is gold,",
    "Only shooting stars...",
    "Somebody once asked could I spare some change for gas?",
    "I need to get myself away from this place.",
    'I said, "Yup" what a concept,',
    "I could use a little fuel myself.",
    "And we could all use a little change.",
    "Well, the years start coming and they don't stop coming.",
    "Fed to the rules and I hit the ground running.",
    "Didn't make sense not to live for fun.",
    "Your brain gets smart but your head gets dumb.",
    "So much to do, so much to see,",
    "so what's wrong with taking the back streets?",
    "You'll never know if you don't go.",
    "You'll never shine if you don't glow.",
    "Hey now, you're an all-star, get your game on, go play.",
    "Hey now, you're a rock star, get the show on, get paid.",
    "All that glitters is gold,",
    "only shooting stars break the mold.",
    "All that glitters is gold,",
    "only shooting stars break the mold.",
  ],
};

let song3Data = {
  title: "Man's Not Hot",
  artist: "Big Shaq",
  genre: "Hip Hop",
  mv_url: "https://www.youtube.com/watch?v=3M_5oYU-IsU",
  lyrics: [
    "Yo, Big Shaq, the one and only.",
    "Man's not hot, never hot.",
    "Skrrat, skidi-kat-kat.",
    "Boom!",
    "Two plus two is four.",
    "Minus one that's three, quick maths.",
    "Everyday man's on the block.",
    "Smoke trees.",
    "See your girl in the park.",
    "That girl is a uckers.",
    "When the ting went quack-quack-quack.",
    "You man were ducking.",
    "Hold tight, Asznee.",
    "He's got the pumpy.",
    "Hold tight, my man.",
    "He's got the frisbee.",
    "I trap, trap, trap on the phone.",
    "Movin' that cornflakes.",
    "Rice Krispies.",
    "Hold tight, my girl Whitney.",
    "On, on, on, on, on the road doin' ten toes.",
    "Like my toes.",
    "You man thought I froze.",
    "I see a peng girl, then I pose.",
    "If she ain't on it, I ghost.",
    "Hah, look at your nose.",
    "You donut.",
    "Nose long like garden hose.",
    "I tell her man's not hot.",
    "I tell her man's not hot.",
    "The girl told me, take off your jacket.",
    "I said, babes, man's not hot.",
    "I tell her man's not hot.",
    "I tell her man's not hot.",
    "The girl told me, take off your jacket.",
    "I said, babes, man's not hot.",
    "Hop out the four-door with the .44.",
    "It was one, two, three and four.",
    "Chillin' in the corridor.",
    "Your dad is forty-four.",
    "And he's still callin' man for a draw.",
    "Let him know.",
    "When I see him.",
    "I'm gonna spin his jaw.",
    "Take man's Twix by force.",
    "Send man's shop by force.",
    "Your girl knows I've got the sauce.",
    "No ketchup.",
    "Just sauce.",
    "Raw sauce.",
    "Ah, yo, boom, ah.",
    "The ting goes skrrrahh.",
    "Pap, pap, ka-ka-ka.",
    "Skidiki pap pap.",
    "And a pu-pu-pudrrrr-boom.",
    "Skya.",
    "Du-du-ku-ku-dun-dun.",
    "Poom, poom.",
    "ou don' know.",
    "I tell her man's not hot.",
    "I tell her man's not hot.",
    "The girl told me, take off your jacket.",
    "I said, babes, man's not hot.",
    "I tell her man's not hot.",
    "I tell her man's not hot.",
    "The girl told me, take off your jacket.",
    "I said, babes, man's not hot.",
    "Man can never be hot.",
    "Perspiration ting.",
    "Lynx Effect.",
    "You didn't hear me, did you?",
    "Use roll-on.",
    "Or spray.",
    "But either way, A-B-C-D.",
    "The ting goes skrrrahh.",
    "Pap, pap, ka-ka-ka.",
    "Skidiki pap pap.",
    "And a pu-pu-pudrrrr-boom.",
    "Skya.",
    "Du-du-ku-ku-dun-dun.",
    "Poom, poom.",
    "You don' know.",
    "Big Shaq.",
    "Man's not hot.",
    "I tell her man's not hot.",
    "40 degrees and man's not hot.",
    "Yo, in the sauna.",
    "Man's not hot.",
    "Yeah, skidika pap pap.",
  ],
};

let song4Data = {
  title: "The Middle",
  artist: "Zedd, Maren Morris, Grey",
  genre: "EDM",
  mv_url: "https://www.youtube.com/watch?v=M3mJkSqZbX4",
  lyrics: [
    "Take a seat.",
    "Right over there,",
    "sat on the stairs.",
    "Stay or leave.",
    "The cabinets are bare",
    "and I'm unaware",
    "of just how we got,",
    "into this mess,",
    "got so aggressive.",
    "I know we meant",
    "all good intentions.",
    "So pull me closer,",
    "why don't you pull me close?",
    "Why don't you come on over?",
    "Cos I can't just let you go.",
    "Baby,",
    "Why don't you just meet me in the middle?",
    "I'm losing my mind just a little.",
    "So why don't you just meet me in the middle?",
    "In the middle...",
    "In the middle!",
    "Baby,",
    "Why don't you just meet me in the middle?",
    "I'm losing my mind just a little.",
    "So why don't you just meet me in the middle?",
    "In the middle...",
    "In the middle!",
    "Take a step.",
    "Back for a minute,",
    "into the kitchen,",
    "floors are wet.",
    "Taps are still running,",
    "dishes are broken.",
    "How did we get,",
    "into this mess,",
    "got so aggressive.",
    "I know we meant",
    "all good intentions.",
    "So pull me closer,",
    "why don't you pull me close?",
    "Why don't you come on over?",
    "Cos I can't just let you go.",
    "Baby,",
    "Why don't you just meet me in the middle?",
    "I'm losing my mind just a little.",
    "So why don't you just meet me in the middle?",
    "In the middle...",
    "In the middle!",
    "Looking at you I can't lie.",
    "Just pouring out admission,",
    "regardless my objection.",
    "And it's not about my pride.",
    "I need you on my skin just,",
    "come over, pull me in just...",
    "Baby,",
    "Why don't you just meet me in the middle?",
    "I'm losing my mind just a little.",
    "So why don't you just meet me in the middle?",
    "In the middle...",
    "In the middle!",
    "Baby,",
    "Why don't you just meet me in the middle?",
    "I'm losing my mind just a little.",
    "So why don't you just meet me in the middle?",
    "In the middle...",
    "In the middle!",
  ],
};
